# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mammon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mammon
	
	pod 'PhoneNumberKit', '~> 3.0'


end

workspace 'ECS 189 projects'